apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: nodejs-alertmanager-config
  labels:
    release: prometheus

spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: slack
    routes:
    - matchers:
      - name: severity
        value: critical
        matchType: =
      receiver: slack
  receivers:
  - name: slack
    slackConfigs:
    - channel: 'alerts'
      apiURL:
        name: slack-webhook
        key: url
      sendResolved: true
      title: {{`'[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'`}}
      text: {{`{{ template "slack.message" . }}` | quote }}
