---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: default
spec:
  encryptedData:
    url: AgB8Sufqljdbb2Dew6aCduIxiTIjSNu6pW9Wc4t188Cl83Z5uVFJXXgWw5xHeaq2Eu1cEfYJ30c0csz46TSDSqiSH6MgrE9t026I3AGVQxx1dyTlBEeRlTYZpuBjwvLMQG5zvlrj0SUMrwl9OrNbSMA9lh9wM5InMksOUHzkihGTBgJx+g37gboJlasDbUsYCJY1QCkbXRhjoc1TkMcQtXYNccdsj9a24YobNat28kptjp3NHlYtsVyOHNp6jaGaMzsO5OMzwZfAd6Qtu2xxcuDUQTc0kQXNqhzvvGwtpkWx3/NK85ZecX3BMFNNVkNeD8/Xt1KwodM8SGCsw4daYkEi9Wccfy2MCgHYfGBIyFSTpGQ9nuM+XHZM0HWQ0tdHOI2rK9JlMgh9Xx3T56nYwr63fRLsor1JlbZgjw6f4CjW+cH0PMS7EwadjsPaJzXO1p7vDVyHG3c7dzI1+ZdhGth0KuxfOaA+t554bNyp/5tpplUvsoXjNyBpdr4RJXNFkQVDO6f24g2pM1LTJHJ1rr77pjoHr3VC5kNfSVWRnTaWc09ot3A1/3gO7xySOZ2MqOF5Snp2vD/wFvkcWwJ9ZON5hG7gRljjTzSWrbdVhVHCL9OAN3Q/PircjKO6gSX6sgY8gKgueG1x1owk375rb6hYfM/sflQwGEMIpg7d6GIKxW+i/22Kd2vy1wJKlb+aYyMuVNi1ZIWAzeh9hyAJQRBUjmWVFtrGXkefNAnTEjpBSFzgOe4XCugkehF9/ii5JTNMvRvKqLpavehZzM6uDPTii1GuH7mjV5/guPJySo4lIcE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        release: prometheus
      name: slack-webhook
      namespace: default
    type: Opaque
