apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-cozy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      backend=864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-backend:0.x,
      frontend=864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-frontend
    # argocd-image-updater.argoproj.io/image-list: frontend=864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/backend.helm.image-tag: deployments.backend.image.tag
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: deployments.frontend.image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    helm:
      parameters:
        - name: deployments.frontend.image.repository
          value: 864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-frontend
        - name: deployments.frontend.image.tag
          value: 0.1.0
        - name: deployments.backend.image.repository
          value: 864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-backend
        - name: deployments.backend.image.tag
          value: 0.1.0
    path: charts/application
    repoURL: git@github.com:thangphan3000/todo-manifests.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
