---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-credentials
  namespace: logging
spec:
  encryptedData:
    s3.client.default.access_key: AgAj9z/xO3FvQ8kqRmgq9v8LVyMpiocVDbBYN0iX2SRmIR6Pgj4VFRk9BASgwRS81aOHbWwM9htWfKHgp+lKP94+kBOpoeDl7zeEE07KofFjyQvjzJ/q2JSnmKaF+eIeqvoXR3RZ3Ba8KaTrwwNvUTu6HX5IlwIJkBWT88HwU8mDTtcEReqLkUuwR4KaSBqZ6z0n0yOWNxr+UfYJaKeMGsBmxC8jz6UWcGtfGlIvap93wyDGWHMCdjLYI4UjTkPbVU5lhHixk7M7/tw4ZWaek9I3Ra/VeB0ByDIGvgdEvAU4LiekSsHC1LhInj/idSkMgWa3LIs4lWG6nMbow4adECD1cJjg+hoJqx0s3MKooeAg301yKr5yv5GHHoiXsfn5zwgr4jairc3dJjaWK193RtatvELavTx1CGgdLfX9OHDKlPVj5Lryn7wL1NTnXwbTLCfs4V4YlhV+DN30sHsRR1Pgcv9bHw+sq/MfOY5KDallK9hoEG8b5+EAh/Ftm2crTZiMQEM8mU8ewRXivN3nlCBG4ngA8txt0xphkSwl1Xer6wDCRnkY/fIfiwHbwsrWpEUk1PHLASXiW9JFN6WusdGOBbD26JrCnmETCmRI4TH81uEllM9rj+vgHaGwTP2j5VwdBWa3X3Xih2iCgVwCe0ymvDZhI49H9xxpwzRMj4UAi3raadrgk+kKFiSqeOpkXNkKQsRP3JKqdiu/UHxKyENLWIr0WQU=
    s3.client.default.secret_key: AgDUyTx4L7ceDLZCBYHGmb7GZoy2zU4BrK3njFkqVwu0etQysbKeAG2P7MwRR11Zk/Gdca0+pc/IL6E4ZLuZn2tTSF6L8UllXZ2nr8QLcKv1ocs3T4yNBqXBmahFKjIPQB5Y+i6QG8H7jnUQmENvktaS5X3KLGLzaujR2wKvAFHUyKV8IxInKDHcaAtO/lGv9BYN2pcaAYuX3p63cFLBoNW9q/dRgzR1a6XAeMfPiPyU0ggEzHP4pDx8T5EezK+04mJ69bkMKssK6YTdF1FrFUFZRMlGAp+PYXQtaBEopoRRM0e6X9kRPni2Ed/jcv55gdBDQ25QgLCuhAmW0Tzps7SjmgkavFEbqnwiI/K7+FGECSFN1tmpanfpWfUp9wVijH8vBzehuuWG2qXih+gREeBoQk/bBpwUNf8cwkngnvNUpHJgMA5LkotvGwJxC2sZlUUgDWD2E69IG3FMaMv52acAnMiNeiBOAJMhkNSt0xcAHpaEFDVu6UFoFjhaOAGMKYX+7bs2wf+sfOVa6rzflE6mxGPsiVqqqtdPoHlgET7D3c21+BpidoVKO9jn+7wdPOWNADRtU5z7ul3n5nwbX216OhRPfUBB20akn9evUm6jCMLmM7v6kwH9q213va0kNrlkNGlr3wGjwbpj0vha6jOIMoxplMwGPnQgSwacUMJlu4jKl3QCNZKYNvbLOcnt1LeX4xhR6wWUtUB6S4KUwKtrSbY8v+O5ATh6zRmzvcWOTt/Nmise2ww6KA==
  template:
    metadata:
      creationTimestamp: null
      name: s3-credentials
      namespace: logging
    type: Opaque
