grafanaDashboardConfigMap:
  name: nodejs-api-dashboard
  namespace: monitoring

serviceMonitor:
  release: prometheus
  matchLabels:
    service: backend
  port: backend-metrics-server
  path: /metrics
  scheme: http
  interval: 15s
