{{- range $service, $config := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $service }}
  labels:
    app: {{ $.Chart.Name }}-{{ $service }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-{{ $service }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}-{{ $service }}
    spec:
      serviceAccountName: {{ $.Values.secretServiceAccountName }}
      containers:
        - name: {{ $service }}
          image: {{ $config.image.repository }}:{{ $config.image.tag }}
          imagePullPolicy: {{ $config.image.pullPolicy }}
          ports:
            - containerPort: {{ $config.port }}
          volumeMounts:
            - name: {{ $config.volumeName }}
              mountPath: /mnt/secrets
              readOnly: true
          env:
            {{- range $config.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $config.secretName }}
                  key: {{ .key }}
            {{- end }}
          resources:
            {{- toYaml $config.resources | nindent 12 }}
          {{- if $config.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ $config.readinessProbe.httpGet.path }}
              port: {{ $config.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ $config.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $config.readinessProbe.periodSeconds }}
            successThreshold: {{ $config.readinessProbe.successThreshold }}
            failureThreshold: {{ $config.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ $config.readinessProbe.timeoutSeconds }}
          {{- end }}
      volumes:
        - name: {{ $config.volumeName }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ $.Values.secretProvider.name }}
{{- end }}
