apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name }}
spec:
  provider: {{ .Values.secretProvider.provider }}
  parameters:
    region: {{ .Values.secretProvider.region }}
    usePodIdentity: {{ .Values.secretProvider.usePodIdentity | quote }}
    objects: |
      - objectName: {{ .Values.secretProvider.objectName }}
        objectType: secretsmanager
        jmesPath:
          {{- range .Values.secretProvider.jmesPath }}
          - path: {{ .path }}
            objectAlias: {{ .objectAlias }}
          {{- end }}
  secretObjects:
    - secretName: {{ .Values.secretProvider.secretObjects.name }}
      type: {{ .Values.secretProvider.secretObjects.type }}
      data:
        {{- range .Values.secretProvider.secretObjects.data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
