---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
spec:
  encryptedData:
    url: AgCbhZcpSzwj8YDmL8xo+M3rZpml3UPjs+SproqoDTvwijYRVdBKGatUC/itGzu3SVc3Kw7lp63YILHhKmhR/qlCThuCNWlvmBGInVHrDVwU3ndjqW9ydL0lzUiCSE2FacZ9c0KPZcAsIrza0QOLyA9DaLTtKl0UtYB0b+59zen5uggR8qvsZwXlXhKXYtK9FxA6P64K+dO4YzwbkRb4B1uhZFi/AHGdxoIJVKJsCHnE0BGCtcvdkOfyCEeDIw73AtS8Z25pnTBdiBANV012eb3CxFf/gx/uUixTNeOwLtGf3XDM59ak8qTsmNIx4twbZvx9AYGc174WI0ynJWlG5tN/fsev3SaOcVyRDHUVt2dXepqCI1e0C0ofsQMBZHG7hV6aS3gGSfmBgrElWWp6VIe/IyMMyrxG048aDvTeyPPhmkdU01o1umxMYaWW4RkBLl7zi4YbYWJKEHZmdZ5686lizAeyoRiMA1JPIRaUgLbZXpfPQwd3klMUoOj8GjwxKkyDGS32I4wVGKLzmB01m5fYG6+pd5tm3AMZLHa/XlCk2UvwPMFGml//jOsv1MFP75Roq9ZbNG+K+HIBMKw0dD3MUUhV4o8DPJ9ZB8A5y6hhOveyOSKOsvzz1J6xHN/3x2VizqlTP9r05B4n2yyJSGQOVFdlO3raUMGHtj2l19iGo+wbKRBo0PWLkogD3sNk+B1KbJiEDVnqL8AzLBtStmk/3IeJ9n050UvfY8Ijzjujt/6GIYaPrY1If5OkoN20DRh0Bf5u1PNVsabciLodVwsknYP2C++3kdgyGaORFW2V/4k=
  template:
    metadata:
      creationTimestamp: null
      labels:
        release: prometheus
      name: slack-webhook
    type: Opaque
