---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: dev
spec:
  encryptedData:
    url: AgBgrRrizpApGRZbakU2hE5zrBxD6JXcLAQzAdXjfQ/Fivp0Bn9FXqty7Sscteu0p+oeWbARczNBh9bKoFp9HMSwcYqljnYOTLfun2Cl9ys3qZIVuuw+yskvYZstBbiMO31ipxaYJOuCzK5havkgS3ROW471S1xDoGVpafVuHlUE/jTUmoo8CYXUELpuCRxTMW9I/XZEOxpsVIPRD9XnuVR3vjeb0/yXAYivIQazhW482lEmmJX6pRfFkHGf9bONV7i5dLoAQavgm5gFYO4Mv43mwFHO3xnBqiM6azFNC40WZb/Y69wKth7n9SF4YqeReh/cbJ395+6rvkSzrxvqZcV1TFJqBbin+uLn7EcOjJ5L28DerbaqkwMgI9sNs7Sk6sZbvjuHe19c2Ni+m7qKXhzdNyXzXAEW5IyRFN9dMLGqxoxWi3DAGKaa7z0tfaJDZLFSLKD5D3EmSC9+44R+zRJBkKkvXSaj64FxbXtVZIBibs78HEFwo/2dEyJ6I6hIW9psD2ByH+buPN6il9GF9gBIHUsZAneC5H7iWFBXTAbSp14wGfzoiukPzx8tDRrKByvMck47brSVqbxvgYZEunuuhpmltZXyNdFaX0TNaYaA8ILqFJBvmZFBPjtig9gDzZNHXlVMxyVBrMAD5UXIKNI73o9cxZ+q9d0Q1jJFe5H5143fMFO6p8wF3AYF2LVxKl+YIV0X/zQFwO8uzqizG77apJmflZtXBkwCpQk/mvBcMykOhH9xUx8Wg6qXtfgzFjBPGe9s2+Pvvyr8vBE7TIDI1XDPeQHnQsY0AHq0nYXt5kw=
  template:
    metadata:
      creationTimestamp: null
      labels:
        release: prometheus
      name: slack-webhook
      namespace: dev
    type: Opaque
