apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      parameters:
        - name: deployments.frontend.image.repository
          value: 864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-frontend
        - name: deployments.frontend.image.tag
          value: 0.1.0
        - name: deployments.backend.image.repository
          value: 864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-frontend
        - name: deployments.backend.image.tag
          value: 0.1.0
    path: charts/logging
    repoURL: git@github.com:thangphan3000/todo-manifests.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
